// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft

#include "../ui.h"
#include "lvgl.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_label_afr = NULL;
lv_obj_t *ui_label_boost = NULL;
lv_obj_t *ui_label_afr_value = NULL;
lv_obj_t *ui_label_boost_value = NULL;
lv_obj_t *ui_boost_sign = NULL;
lv_obj_t *ui_lap_timer_label = NULL;
lv_obj_t *ui_lap_timer_value = NULL;
lv_obj_t *ui_lap_timer_delta = NULL;

static lv_point_t line_points[] = {
    {0, 315},      // start (left middle)
    {480, 315}     // end (right middle)
};

void ui_Screen1_screen_init(void)
{
   LV_FONT_DECLARE(Doto_Extra_Bold_84);
   LV_FONT_DECLARE(Schoolbell_24);
   ui_Screen1 = lv_obj_create(NULL);
   lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

   // lv_obj_set_style_bg_color(ui_Screen1,lv_color_black(),LV_PART_MAIN);

   // lv_obj_t * divider = lv_line_create(ui_Screen1);
   // lv_line_set_points(divider, line_points, 2);

   // lv_obj_set_style_line_width(divider, 4, 0); 
   // lv_obj_set_style_line_color(divider, lv_palette_main(LV_PALETTE_PURPLE), 0);
   // lv_obj_set_style_line_opa(divider, LV_OPA_COVER, 0);

   ui_label_afr = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_label_afr, LV_SIZE_CONTENT); 
   lv_obj_set_height( ui_label_afr, LV_SIZE_CONTENT);   
   lv_obj_set_x( ui_label_afr, 0 );
   lv_obj_set_y( ui_label_afr, -100 );
   lv_obj_set_align( ui_label_afr, LV_ALIGN_CENTER );
   lv_label_set_text(ui_label_afr,"AFR");
   lv_obj_set_style_text_color(ui_label_afr, lv_color_white(), LV_PART_MAIN);
   lv_obj_set_style_text_font(ui_label_afr, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_label_boost = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_label_boost, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_label_boost, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_label_boost, 0 );
   lv_obj_set_y( ui_label_boost, 200 );
   lv_obj_set_align( ui_label_boost, LV_ALIGN_CENTER );
   lv_label_set_text(ui_label_boost,"Boost(PSI)");
   lv_obj_set_style_text_color(ui_label_boost, lv_color_white(), LV_PART_MAIN);
   lv_obj_set_style_text_font(ui_label_boost, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);


   ui_lap_timer_label = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_lap_timer_label, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_lap_timer_label, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_lap_timer_label, 0 );
   lv_obj_set_y( ui_lap_timer_label, 45 );
   lv_obj_set_align( ui_lap_timer_label, LV_ALIGN_CENTER );
   lv_label_set_text(ui_lap_timer_label,"Lap Timer");
   lv_obj_set_style_text_color(ui_lap_timer_label, lv_color_white(), LV_PART_MAIN);
   lv_obj_set_style_text_font(ui_lap_timer_label, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);


   ui_label_afr_value = lv_label_create(ui_Screen1);
   //lv_obj_set_width( ui_label_afr_value, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_width(ui_label_afr_value, 240);
   lv_label_set_long_mode(ui_label_afr_value, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_label_afr_value, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_label_afr_value, -10 );
   lv_obj_set_y( ui_label_afr_value, -170 );
   lv_obj_set_align( ui_label_afr_value, LV_ALIGN_CENTER );
   lv_label_set_text(ui_label_afr_value,"0");
   lv_obj_set_style_text_align(ui_label_afr_value, LV_TEXT_ALIGN_CENTER, 0);
   lv_obj_set_style_text_font(ui_label_afr_value, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_label_boost_value = lv_label_create(ui_Screen1);
   //lv_obj_set_width( ui_label_boost_value, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_width(ui_label_boost_value, 240);
   lv_label_set_long_mode(ui_label_boost_value, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_label_boost_value, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_label_boost_value, -10 );
   lv_obj_set_y( ui_label_boost_value, 130 );
   lv_obj_set_align( ui_label_boost_value, LV_ALIGN_CENTER );
   lv_label_set_text(ui_label_boost_value,"0");
   lv_obj_set_style_text_font(ui_label_boost_value, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);
   lv_obj_set_style_text_align(ui_label_boost_value, LV_TEXT_ALIGN_CENTER, 0);

   ui_boost_sign = lv_label_create(ui_Screen1);
   lv_label_set_text(ui_boost_sign, "-");
   lv_obj_set_style_text_font(ui_boost_sign, &Doto_Extra_Bold_84, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_align(ui_boost_sign, LV_ALIGN_CENTER);
   lv_obj_set_x(ui_boost_sign, -140);
   lv_obj_set_y(ui_boost_sign, 130);
   lv_obj_set_style_text_opa(ui_boost_sign, LV_OPA_TRANSP, 0);
   lv_obj_set_style_text_color(ui_boost_sign, lv_color_hex(0x28FF00), LV_PART_MAIN);

   ui_lap_timer_value = lv_label_create(ui_Screen1);
   lv_label_set_text(ui_lap_timer_value, "1:52.09");
   //lv_obj_set_width(ui_lap_timer_value, 440);
   lv_obj_set_style_text_font(ui_lap_timer_value, &Doto_Extra_Bold_84, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_align(ui_lap_timer_value, LV_ALIGN_CENTER);
   lv_obj_set_x(ui_lap_timer_value, 5);
   lv_obj_set_y(ui_lap_timer_value, -25);
   lv_obj_set_style_text_color(ui_lap_timer_value, lv_palette_main(LV_PALETTE_CYAN), LV_PART_MAIN);


   // ui_lap_timer_delta = lv_label_create(lv_scr_act());
   // lv_obj_align(ui_lap_timer_delta, LV_ALIGN_TOP_LEFT, 10, 40);
}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_label_afr= NULL;
ui_label_boost= NULL;
ui_label_afr_value= NULL;
ui_label_boost_value= NULL;
ui_boost_sign= NULL;
ui_lap_timer_value= NULL;
ui_lap_timer_delta= NULL;

}
