// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft

#include "../ui.h"
#include "lvgl.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *fuel_arc = NULL;lv_obj_t *ui_Image1 = NULL;

void ui_Screen1_screen_init(void)
{
   LV_FONT_DECLARE(Doto_Extra_Bold_84);
   LV_FONT_DECLARE(Schoolbell_24);
   ui_Screen1 = lv_obj_create(NULL);
   lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

   lv_obj_set_style_bg_color(ui_Screen1,lv_color_black(),LV_PART_MAIN);

   ui_Label1 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label1, 0 );
   lv_obj_set_y( ui_Label1, -60 );
   lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label1,"AFR");
   lv_obj_set_style_text_font(ui_Label1, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label2 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label2, 0 );
   lv_obj_set_y( ui_Label2, 150 );
   lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label2,"Boost(PSI)");
   lv_obj_set_style_text_font(ui_Label2, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label5 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
   //lv_obj_set_width(ui_Label5, 140);
   lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label5, 0 );
   lv_obj_set_y( ui_Label5, -130 );
   lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label5,"0");
   lv_obj_set_style_text_font(ui_Label5, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label6 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
   //lv_obj_set_width(ui_Label6, 140);
   lv_label_set_long_mode(ui_Label6, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label6, 0 );
   lv_obj_set_y( ui_Label6, 80 );
   lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label6,"0");
   lv_obj_set_style_text_font(ui_Label6, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);
}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Label3= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_Label8= NULL;

}
