// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_label_boost;
extern lv_obj_t *ui_label_afr;
extern lv_obj_t *ui_label_afr_value;
extern lv_obj_t *ui_label_boost_value;
extern lv_obj_t *ui_boost_sign;
extern lv_obj_t *ui_lap_timer_label;
extern lv_obj_t *ui_lap_timer_value;
extern lv_obj_t *ui_lap_timer_delta;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

