// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft
#include "ui.h"
#include "ui_helpers.h"
#include "boot/boot_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

TireWidget tire_FL;
TireWidget tire_FR;
TireWidget tire_RL;
TireWidget tire_RR;

screen_t currentScreen =
    SCREEN_GAUGES;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void boot_starter(){
    lv_scr_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 1000, false);
}

void ui_init( void ){
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    // boot_screen_create();
    // lv_obj_add_event_cb(boot_screen, boot_starter, LV_EVENT_SCREEN_LOADED, NULL);
    // boot_start();
    currentScreen = SCREEN_GAUGES;

    lv_disp_load_scr(ui_Screen1);
}

void ui_destroy( void ){
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
}
