// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft

#ifndef _STIGAUGECIRCLELEFT_UI_H
#define _STIGAUGECIRCLELEFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif
    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// extern const lv_img_dsc_t ui_img_sti_logo_png;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_sti_logo_png);  
// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
